//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarsiLibrary.WPFDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FarsiLibrary.WPFDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Format the date displayed in DatePicker, you can assign a new IValueConverter instance and format the DateTime value. You need to set the converter to DateConverter property of the FXDatePicker control..
        /// </summary>
        internal static string DateConverterParagraph {
            get {
                return ResourceManager.GetString("DateConverterParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farsi.
        /// </summary>
        internal static string Farsi {
            get {
                return ResourceManager.GetString("Farsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        internal static string Flow {
            get {
                return ResourceManager.GetString("Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Enabled.
        /// </summary>
        internal static string IsEnabled {
            get {
                return ResourceManager.GetString("IsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian Date.
        /// </summary>
        internal static string PersianDate {
            get {
                return ResourceManager.GetString("PersianDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Date.
        /// </summary>
        internal static string SelectedDate {
            get {
                return ResourceManager.GetString("SelectedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Date to Null.
        /// </summary>
        internal static string SetDateNull {
            get {
                return ResourceManager.GetString("SetDateNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Date to 2008/02/25.
        /// </summary>
        internal static string SetDateSpecific {
            get {
                return ResourceManager.GetString("SetDateSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Date to Today.
        /// </summary>
        internal static string SetDateToday {
            get {
                return ResourceManager.GetString("SetDateToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Empty Button.
        /// </summary>
        internal static string ShowEmptyButton {
            get {
                return ResourceManager.GetString("ShowEmptyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Today Button.
        /// </summary>
        internal static string ShowTodayButton {
            get {
                return ResourceManager.GetString("ShowTodayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show WeekDay Names.
        /// </summary>
        internal static string ShowWeekNames {
            get {
                return ResourceManager.GetString("ShowWeekNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FXMonthView.
        /// </summary>
        internal static string Title_FXMonthView {
            get {
                return ResourceManager.GetString("Title_FXMonthView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farsi Library v2.5.
        /// </summary>
        internal static string VersionTitle {
            get {
                return ResourceManager.GetString("VersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Date.
        /// </summary>
        internal static string ViewDate {
            get {
                return ResourceManager.GetString("ViewDate", resourceCulture);
            }
        }
    }
}
